name: "Estratti OSM"
description: ""

url: "http://osm-toolserver-italia.wmflabs.org/estratti/"
baseurl: "/estratti"

paginate: 10

markdown: rdiscount
permalink: pretty
highlighter: pygments

permalink: /:categories/:title/

lang:
  it:
    home: "Home"
    regioni: "Regioni"
    comuni: "Comuni"
    note: "Note"
  en:
    home: "Home"
    regioni: "Regions"
    comuni: "Municipalities"
    note: "Notes"
